name: Python package and test

on:
  push:
  pull_request:

jobs:
  checkout-test:
    name: Checkout and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create python 3.9 conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          activate-environment: donkey
          auto-activate-base: false
      - name: Conda install and list
        run: |
          conda info
          conda list
      - name: Install donkey
        run: | 
          pip install -e .[pc,dev]
          pip list
      - name: Run tests
        run: pytest
